version: '3'
services:
  web:
    build: 
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 8888:80
    depends_on:
      - 'db'
    networks:
      - app-net
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: daole
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: travel_service
    networks:
      - app-net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
networks:
  app-net:
